title: Dai Wang's Homepage
page-top-title: Dai Wang
top-section-bg-text: Artificial Intelligence
home-subtitle: Dai Wang&entp;|&entp;王黛
copyright-text: '&copy; Dai Wang 2022-2025. All Rights Reserved.'
